language: c++
compiler: g++

services:
  - docker

env:
  - ARCH=x86_64 DOCKER_IMAGE=quay.io/appimage/appimagebuild
  - ARCH=i686 DOCKER_IMAGE=quay.io/appimage/appimagebuild-i386

script:
  - mkdir -p ./out/
  - docker run -i -v ${PWD}/out:/out -v "${PWD}:/AppImageKit-dialog" "$DOCKER_IMAGE" /bin/bash -c "/AppImageKit-dialog/build.sh ; cp /AppImageKit-dialog/src/dialog out/dialog-${ARCH}"

after_success:
  - ls -lh out/*
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash ./upload.sh out/*

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
